# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a smaller image for the final build
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules

# Set the environment variables for App Store Connect API
ENV APP_STORE_CONNECT_KEY_ID=YOUR_KEY_ID
ENV APP_STORE_CONNECT_ISSUER_ID=YOUR_ISSUER_ID
ENV APP_STORE_CONNECT_P8_PATH=/path/to/your/auth-key.p8

# Run the server
CMD ["node", "dist/src/index.js"]
